services:
  nextcloud:
    image: nextcloud/all-in-one
    ports:
      - 8080:80
    volumes:
      - ./data:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=your_mysql_password
      - NEXTCLOUD_TRUSTED_DOMAINS=your_domain
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=your_admin_password
    depends_on:
      - nextcloud-db
    restart: unless-stopped

  # nextcloud-db:
  #   image: mariadb:latest
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=your_mysql_root_password
  #     - MYSQL_DATABASE=nextcloud
  #     - MYSQL_USER=nextcloud
  #     - MYSQL_PASSWORD=your_mysql_password
  #   volumes:
  #     - nextcloud-db:/var/lib/mysql
  #   restart: unless-stopped

  # nextcloud-proxy:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./certs:/etc/nginx/certs:ro
  #     - ./dhparam:/etc/nginx/dhparam:ro
  #   depends_on:
  #     - nextcloud
  #   restart: unless-stopped

volumes:
  nextcloud-data:
  nextcloud-db:
