services:
  laravel:
    image: bitnami/laravel
    # build: .
    container_name: lv_bitnami
    restart: on-failure:1
    # volumes:
      # - ./src:/app
      # - ./lib/:/opt/bitnami/php/lib/ # ab version 8 geht php.ini nicht mehr
      # ports:
      # - host:cont
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.bitnami.rule=Host(`$LARAVEL_URL`)
      - traefik.http.routers.bitnami-secure.rule=Host(`$LARAVEL_URL`)
      - traefik.http.routers.bitnami.entrypoints=$ENTRYPOINT
      - traefik.http.routers.bitnami-secure.entrypoints=$SECURE_ENTRYPOINT

      - traefik.http.routers.bitnami-secure.service=bitnami
      - traefik.http.routers.bitnami-secure.tls=true
      - traefik.http.routers.bitnami-secure.tls.certresolver=$CERTRESOLVER
      - traefik.http.routers.bitnami-secure.middlewares=secHeaders@file
      - traefik.http.services.bitnami.loadbalancer.server.port=8000
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=$MARIADB_USER
      - DB_DATABASE=$MARIADB_DATABASE
      - DB_PASSWORT=$MARIADB_PASSWORD
    # command:
    #  - apt update && apt install php mysql && systemctl restart nginx
    networks:
      - traefik
      - laravel_backend

  redis:
    image: redis
    container_name: lv_bitnami_redis
    restart: on-failure:1
    ports:
      - 16379:6379
    volumes:
      - ./redis:/data

  mariadb:
    image: docker.io/bitnami/mariadb
    container_name: lv_bitnami_db
    restart: on-failure:1
    environment:
      - ALLOW_EMPTY_PASSWORD # is recommended only for development.
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_DATABASE=$MARIADB_DATABASE
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD=$MARIADB_PASSWORD
    networks:
      - laravel_backend

networks:
  traefik:
    external: true
  laravel_backend:
