services:
  reachable:
    # image: bitnami/laravel
    build: .
    container_name: lv_reachable
    restart: none
    volumes:
      - ./src:/app
      # - ./lib/:/opt/bitnami/php/lib/ # ab version 8 geht php.ini nicht mehr
      # ports:
      # - host:cont
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.reachable.rule=Host(`$LARAVEL_URL`)
      - traefik.http.routers.reachable-secure.rule=Host(`$LARAVEL_URL`)
      - traefik.http.routers.reachable.entrypoints=$ENTRYPOINT
      - traefik.http.routers.reachable-secure.entrypoints=$SECURE_ENTRYPOINT

      - traefik.http.routers.reachable-secure.service=reachable
      - traefik.http.routers.reachable-secure.tls=true
      - traefik.http.routers.reachable-secure.tls.certresolver=$CERTRESOLVER
      - traefik.http.routers.reachable-secure.middlewares=secHeaders@file
      - traefik.http.services.reachable.loadbalancer.server.port=8000
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=$MARIADB_USER
      - DB_DATABASE=$MARIADB_DATABASE
      - DB_PASSWORT=$MARIADB_PASSWORD
    # command:
    #  - apt update && apt install php mysql && systemctl restart nginx
    networks:
      - traefik
      - laravel_backend

  redis:
    image: redis
    container_name: lv_reachable_redis
    restart: none
    ports:
      - 16379:6379
    volumes:
      - ./redis:/data

  mariadb:
    image: docker.io/bitnami/mariadb
    container_name: lv_reachable_db
    restart: none
    environment:
      # - ALLOW_EMPTY_PASSWORD # is recommended only for development.
      - MARIADB_USER=$MARIADB_USER
      - MARIADB_DATABASE=$MARIADB_DATABASE
      - MARIADB_PASSWORD=$MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD=$MARIADB_PASSWORD
    networks:
      - laravel_backend

networks:
  traefik:
    external: true
  laravel_backend:
