networks:
  table:
    external: true
  traefik:
    external: true

volumes:
  dbdata:
    driver: local

services:
  nginx:
    image: nginx
    # build:
      # context: .
      # dockerfile: nginx/Dockerfile
    container_name: table_nginx
    restart: always
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./src/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./crontab:/etc/crontab:rw
      # - ./cron:/etc/cron.d:rw
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.table.rule=Host(`$LARAVEL_URL`)
      - traefik.http.routers.table-secure.rule=Host(`$LARAVEL_URL`)
      - traefik.http.routers.table.entrypoints=$ENTRYPOINT
      - traefik.http.routers.table-secure.entrypoints=$SECURE_ENTRYPOINT

      - traefik.http.routers.table-secure.service=table
      - traefik.http.routers.table-secure.tls=true
      - traefik.http.routers.table-secure.tls.certresolver=$CERTRESOLVER
      - traefik.http.routers.table-secure.middlewares=secHeaders@file
      - traefik.http.services.table.loadbalancer.server.port=80
      # ports:
      # - "81:80"
      # - "5173:5173" # Vite port
    depends_on:
      - php
      - db
    networks:
      - table
      - traefik

  db:
    image: mysql
    container_name: table_db
    restart: always
    tty: true
    expose:
      - "3306"
    volumes:
      - ./mysql/data:/var/lib/mysql # Db Ordner-Pfad korrekt
      # - ./mysql/mysql.cnf:/etc/mysql/my.cnf #Konfigdatei-Pfad korrekt
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/fhem-init.sql
    environment:
      MYSQL_DATABASE: $MARIADB_DATABASE #optional
      MYSQL_USER: $MARIADB_USER
      MYSQL_PASSWORD: $MARIADB_PASSWORD
      MYSQL_ROOT_PASSWORD: $MARIADB_PASSWORD
      MYSQL_ONETIME_PASSWORD: false
    networks:
      - table

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: table_php
    volumes:
      - ./src:/var/www/html
      # - ./cron:/etc/cron.d/root
    ports:
      - "9100:9100"
    networks:
      - table

  composer:
    image: composer:latest
    container_name: table_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - table

  npm:
    image: node:latest
    container_name: table_npm
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - table

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: table_artisan
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - db
    working_dir: /var/www/html
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - table
