networks:
  reachable:
    external: true
  traefik:
    external: true

volumes:
  dbdata:
    driver: local

services:
  nginx:
    # image: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: reachable_nginx
    restart: always
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./src/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./crontab:/etc/crontab:rw
      # - ./cron:/etc/cron.d:rw
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.reachable.rule=Host(`$LARAVEL_URL`)
      - traefik.http.routers.reachable-secure.rule=Host(`$LARAVEL_URL`)
      - traefik.http.routers.reachable.entrypoints=$ENTRYPOINT
      - traefik.http.routers.reachable-secure.entrypoints=$SECURE_ENTRYPOINT

      - traefik.http.routers.reachable-secure.service=reachable
      - traefik.http.routers.reachable-secure.tls=true
      - traefik.http.routers.reachable-secure.tls.certresolver=$CERTRESOLVER
      - traefik.http.routers.reachable-secure.middlewares=secHeaders@file
      - traefik.http.services.reachable.loadbalancer.server.port=80
      # ports:
      # - "81:80"
      # - "5173:5173" # Vite port
    depends_on:
      - php
      - db
    networks:
      - reachable
      - traefik

  db:
    image: mysql
    container_name: reachable_db
    restart: always
    tty: true
    expose:
      - "3306"
    volumes:
      - ./mysql/data:/var/lib/mysql # Db Ordner-Pfad korrekt
      - ./mysql/mysql.cnf:/etc/mysql/my.cnf #Konfigdatei-Pfad korrekt
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/fhem-init.sql
    environment:
      MYSQL_DATABASE: $MARIADB_DATABASE #optional
      MYSQL_USER: $MARIADB_USER
      MYSQL_PASSWORD: $MARIADB_PASSWORD
      MYSQL_ROOT_PASSWORD: $MARIADB_PASSWORD
      MYSQL_ONETIME_PASSWORD: false
    networks:
      - reachable

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reachable_php
    volumes:
      - ./src:/var/www/html
      # - ./cron:/etc/cron.d/root
    ports:
      - "9100:9100"
    networks:
      - reachable

  # scheduler:
  #   build:
  #     context: .
  #     dockerfile: Supervisor
  #   container_name: reachable_scheduler
  #   environment:
  #     - TZ=Europe/Berlin
  #   volumes:
  #     - ./src:/var/www/html:delegated
  #     # - ./nginx_crontab:/etc/crontab:rw
  #   depends_on:
  #     - nginx
  #   working_dir: /var/www/html
  #   # entrypoint: [ 'php', '/var/www/html/artisan' ]
  #   # command: schedule:run
  #   networks:
  #     - laravel

  composer:
    image: composer:latest
    container_name: reachable_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - reachable

  npm:
    image: node:latest
    container_name: reachable_npm
    volumes:
      - ./src:/var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]
    networks:
      - reachable

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reachable_artisan
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - db
    working_dir: /var/www/html
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - reachable
