services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/app/data
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.uptime-secure.service=uptime
      - traefik.http.routers.uptime.entrypoints=$ENTRYPOINT
      - traefik.http.routers.uptime-secure.entrypoints=$SECURE_ENTRYPOINT
      - traefik.http.routers.uptime.rule=Host(`$URL`)
      - traefik.http.routers.uptime-secure.rule=Host(`$URL`)
      - traefik.http.routers.uptime-secure.tls=true
      - traefik.http.routers.uptime-secure.tls.certresolver=$CERTRESOLVER
      - traefik.http.routers.uptime-secure.middlewares=secHeaders@file
      - traefik.http.services.uptime.loadbalancer.server.port=3001
    networks:
      - traefik
networks:
  traefik:
    external: true
