services:
  prometheus:
    image: docker.io/bitnami/prometheus:2
    container_name: pm
    restart: unless-stopped
    volumes:
      - ./data:/opt/bitnami/prometheus/data
      - ./conf:/etc/prometheus
    ports:
      - '9090:9090'
